package game

const (
	NAME         = "NAME"
	CATEGORYID   = "CATEGORYID"
	CATEGORIES   = "CATEGORIES"
	QUESTION     = "QUESTION"
	ANSWER_LIE   = "ANSWER_LIE"
	ANSWER_TRUTH = "ANSWER_TRUTH"
	ANSWERID     = "ANSWERID"
	SCORE        = "SCORE"
)
