version: '3'
services:
  nats:
    image: nats
    ports:
      - 4222:4222
  etcd:
    image: appcelerator/etcd
    ports:
      - 2379:2379
  server:
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    restart: unless-stopped
    ports:
      - "3250:3250"
      - "80:80"
