apiVersion: v1
kind: Service
metadata:
  labels:
    app: fibbage-game
  name: websocket-game-service
  annotations:
    cloud.google.com/backend-config: '{"ports": {"3250":"my-wsc-backendconfig"}}'
spec:
  type: NodePort
  ports:
    - port: 3250
      protocol: TCP
      targetPort: 3250
  selector:
    app: fibbage-game

