apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibbage-backend
spec:
  selector:
    matchLabels:
      app: fibbage-game
  replicas: 1
  template:
    metadata:
      labels:
        app: fibbage-game
    spec:
      containers:
        - name: fibbage-game-server
          env:
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: password
            - name: DB_HOST
              value: mysql.default.svc.cluster.local
            - name: PITAYA_CLUSTER_RPC_CLIENT_NATS_CONNECT
              value: nats.default.svc.cluster.local
            - name: PITAYA_CLUSTER_RPC_SERVER_NATS_CONNECT
              value: nats.default.svc.cluster.local
            - name: PITAYA_CLUSTER_SD_ETCD_ENDPOINTS
              value: etcd.default.svc.cluster.local:2379
            - name: PITAYA_GROUPS_ETCD_ENDPOINTS
              value: etcd.default.svc.cluster.local:2379
            - name: PITAYA_MODULES_BINDINGSTORAGE_ETCD_ENDPOINTS
              value: etcd.default.svc.cluster.local:2379
          image: redax/fibbage-game-server
          ports:
            - containerPort: 3250




