apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: websocket-repeater
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
     - http:
        paths:
          - path: /
            backend:
              serviceName: websocket-game-service
              servicePort: 3250
          - path: /game
            backend:
              serviceName: fibbage-frontend-service
              servicePort: 8080
